# Generated by Django 6.0.2 on 2026-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('regions', models.JSONField(default=list)),
                ('diseases', models.JSONField(default=list)),
                ('species', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
            ],
        ),
    ]
