# Generated by Django 6.0.2 on 2026-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="external_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
